-- Review 테이블
CREATE TABLE REVIEW (
    REVIEW_ID   NUMBER PRIMARY KEY,
    RECIPE_ID   NUMBER NOT NULL,
    APPUSERID   NUMBER NOT NULL,
    RATING      NUMBER NOT NULL,
    COMMENT_TEXT    CLOB   ,
    CREATED_AT  DATE DEFAULT SYSDATE,
    UPDATED_AT  DATE
    CONSTRAINT fk_review_recipe FOREIGN KEY (recipe_id) REFERENCES Recipes(recipe_id),
    CONSTRAINT fk_review_user FOREIGN KEY (appuserid) REFERENCES AppUsers(appuserid)
);
--삭제
DROP TABLE REVIEW CASCADE CONSTRAINTS;

DESC RECIPES;
DESC APPUSERS;

-- ReviewSummary 테이블 (평점 집계용 캐시)
CREATE TABLE REVIEWSUMMARY (
    SUMMARY_ID   NUMBER PRIMARY KEY,
    RECIPE_ID    NUMBER NOT NULL,
    AVG_RATING   NUMBER(3,2),
    REVIEW_COUNT NUMBER,
    DISTRIBUTION CLOB,
    UPDATED_AT   DATE DEFAULT SYSDATE,
    CONSTRAINT FK_SUMMARY_RECIPE FOREIGN KEY (RECIPE_ID) REFERENCES RECIPES(RECIPE_ID)
);
 
--삭제
DROP TABLE REVIEWSUMMARY CASCADE CONSTRAINTS;


-- Comment 테이블
CREATE TABLE COMMENTS (
    COMMENT_ID   NUMBER PRIMARY KEY,
    REVIEW_ID    NUMBER NOT NULL,
    APPUSERID    NUMBER NOT NULL,
    CONTENT      CLOB,
    CREATED_AT   DATE DEFAULT SYSDATE,
    UPDATED_AT   DATE,
    PARENT_ID    NUMBER 
    CONSTRAINT FK_COMMENT_REVIEW FOREIGN KEY (REVIEW_ID) REFERENCES REVIEW(REVIEW_ID),
    CONSTRAINT FK_COMMENT_USER   FOREIGN KEY (APPUSERID) REFERENCES APPUSERS(APPUSERID),
    CONSTRAINT FK_COMMENT_PARENT FOREIGN KEY (PARENT_ID) REFERENCES COMMENTS(COMMENT_ID)
);
 

--삭제
DROP TABLE REVIEWSUMMARY CASCADE CONSTRAINTS;


INSERT INTO review (review_id, recipe_id, appuserid, rating, comment_text, created_at, updated_at)
VALUES (1, 1, 1, 5, '맛있어요', SYSDATE, SYSDATE);


INSERT INTO comments (comment_id, review_id, appuserid, content, created_at, updated_at, parent_id)
VALUES (1, 1, 2, '저도 동의합니다', SYSDATE, SYSDATE, 1);






-- 희재
CREATE TABLE BUG3(	
APPUSERID                              NUMBER                                        NOT NULL,	
PASSWORD                              VARCHAR2(100),	
PROVIDER                                VARCHAR2(100)                            NOT NULL,	
PROVIDER_ID                          VARCHAR2(100),	
	
NICKNAME                               VARCHAR2(50),	
EMAIL                                       VARCHAR2(100),	
MOBILE                                    VARCHAR2(20),	
BFILE                                       VARCHAR2(225),	
JOINDATE                               DATE                                                 DEFAULT SYSDATE,	
	
CONSTRAINT PK_BUG3 PRIMARY KEY (APPUSERID,EMAIL,NICKNAME),	
CONSTRAINT UK_BUG3_SOCIAL UNIQUE (PROVIDER, PROVIDER_ID)	
);	



--상현
-- RECIPES 테이블
CREATE TABLE recipes3 (
    RECIPE_ID    NUMBER PRIMARY KEY,
    APPUSERID    NUMBER NOT NULL,
    TITLE        VARCHAR2(255) NOT NULL,
    CATEGORY     NUMBER, 
    IMAGE        VARCHAR2(255) DEFAULT 'no.png',
    COOK_TIME    NUMBER DEFAULT 0,
    DIFFICULTY   VARCHAR2(50),
    SERVINGS     NUMBER DEFAULT 1,
    DESCRIPTION  VARCHAR2(4000),
    INSTRUCTIONS VARCHAR2(4000),
    CREATED_AT   DATE DEFAULT SYSDATE,
    UPDATED_AT   DATE,
    VIEWS        NUMBER DEFAULT 0,
    R_URL        VARCHAR2(255),         -- 유튜브 링크용
    STATUS VARCHAR2(20) DEFAULT 'ACTIVE', -- 삭제/비공개 대비
    IS_MALICIOUS CHAR(1) DEFAULT 'N' ,  -- 악성 내용 판별 결과 저장하고 싶다면 
    IS_AI_GENERATED CHAR(1) DEFAULT 'N' -- AI 자동 생성 여부 표시
);

CREATE TABLE CATEGORY3 (
   CATEGORY      NUMBER PRIMARY KEY,
   CATEGORY_NAME VARCHAR2(100)
);




-- 리뷰 시퀀스
CREATE SEQUENCE seq_REVIEW;

-- 평점집계용 시퀀스
CREATE SEQUENCE seq_REVIEWSUMMARY;

-- 코멘트 시퀀스
CREATE SEQUENCE seq_COMMENTS;