-- 테스트용 질문 데이터 하나 넣어보기
INSERT INTO RECIPE_QUESTIONS (Q_ID, STEP_NO, TITLE, DESCRIPTION)
VALUES (seq_rec_q.NEXTVAL, 1, '어떤 식사를 원하시나요?', '오늘의 첫 끼니를 골라보세요.');

COMMIT;




-- 추천 질문 테이블	
CREATE TABLE RECIPE_QUESTIONS (	
Q_ID        NUMBER PRIMARY KEY,	
STEP_NO     NUMBER NOT NULL,      -- 1, 2, 3, 4 순서	
TITLE       VARCHAR2(255) NOT NULL, -- 질문 (예: 어떤 식사를 원하시나요?)	
DESCRIPTION VARCHAR2(500),         -- 설명	
 NEXT_STEP   NUMBER,                 -- 클릭 시 이동할 다음 STEP_NO
CREATED_AT  DATE DEFAULT SYSDATE	
);	


	
-- 추천 선택지 테이블	
CREATE TABLE RECIPE_OPTIONS (	
OPT_ID      NUMBER PRIMARY KEY,	
Q_ID        NUMBER NOT NULL,	
OPT_LABEL   VARCHAR2(100) NOT NULL, -- 화면 표시 (예: 아침 식사)	
OPT_VALUE   VARCHAR2(100) NOT NULL, -- 로직용 값 (예: BREAKFAST)	
FOREIGN KEY (Q_ID) REFERENCES RECIPE_QUESTIONS(Q_ID) ON DELETE CASCADE	
);	
	
CREATE SEQUENCE seq_rec_q START WITH 1 INCREMENT BY 1;	
CREATE SEQUENCE seq_rec_opt START WITH 1 INCREMENT BY 1;	
	
	
-- 레시피-선택지 매핑 테이블	
CREATE TABLE RECIPE_TAG_MAP (	
MAP_ID      NUMBER PRIMARY KEY,	
RECIPE_ID   NUMBER NOT NULL,	
OPT_VALUE   VARCHAR2(100) NOT NULL, -- 'BREAKFAST', 'KOREAN' 등	
FOREIGN KEY (RECIPE_ID) REFERENCES RECIPES3(RECIPE_ID) ON DELETE CASCADE	
);	
	
CREATE SEQUENCE seq_rec_tag_map START WITH 1 INCREMENT BY 1;	
	
	
-- 사용자 추천 로그 테이블	
CREATE TABLE RECIPE_SURVEY_LOG (	
LOG_ID      NUMBER PRIMARY KEY,	
APPUSERID   NUMBER NOT NULL,	
SELECTED_OPTS VARCHAR2(1000),     -- 선택한 옵션들 (JSON이나 콤마 구분자)	
RESULT_COUNT  NUMBER,             -- 당시 추천된 레시피 개수	
CREATED_AT  DATE DEFAULT SYSDATE,	
FOREIGN KEY (APPUSERID) REFERENCES BUG3(APPUSERID) ON DELETE CASCADE	
);	
	
CREATE SEQUENCE seq_rec_survey_log START WITH 1 INCREMENT BY 1;	


SELECT * FROM RECIPE_QUESTIONS;

-- 기존에 만드신 OPT_LABEL, OPT_VALUE 컬럼명에 맞춰서 넣기
INSERT INTO RECIPE_OPTIONS (OPT_ID, Q_ID, OPT_LABEL, OPT_VALUE)
VALUES (seq_rec_opt.NEXTVAL, 1, '아침 식사', 'BREAKFAST');

INSERT INTO RECIPE_OPTIONS (OPT_ID, Q_ID, OPT_LABEL, OPT_VALUE)
VALUES (seq_rec_opt.NEXTVAL, 1, '점심 식사', 'LUNCH');

INSERT INTO RECIPE_OPTIONS (OPT_ID, Q_ID, OPT_LABEL, OPT_VALUE)
VALUES (seq_rec_opt.NEXTVAL, 1, '저녁 식사', 'DINNER');

INSERT INTO RECIPE_OPTIONS (OPT_ID, Q_ID, OPT_LABEL, OPT_VALUE)
VALUES (seq_rec_opt.NEXTVAL, 1, '간식/디저트', 'DESSERT');

DELETE FROM RECIPE_OPTIONS WHERE OPT_LABEL IN ('간단한 아침', '든든한 점심', '특별한 저녁');
COMMIT;

COMMIT;

ALTER TABLE RECIPE_OPTIONS ADD NEXT_STEP NUMBER;
COMMIT;